Blog/blog/accounts/urls.py
from django.conf.urls import url
from .import views

app_name = "accounts"

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),

]

Blog/blog/articles/urls.py
from django.conf.urls import url
from .import views


app_name = "articles"

urlpatterns = [
    url(r'^$',views.article_list,name="list"),
    url(r'^(?P<slug>[\w_]+)/$',views.article_details,name="detail"),
]

Blog/blog/blog/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from .import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^articles/',include('articles.urls')),
    url(r'^about/$',views.about),
    url(r'^$',views.homepage),
]


urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Blog/blog/accounts/models.py
from django.db import models

# Create your models here.

Blog/blog/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title=models.CharField(max_length=100)
    slug= models.SlugField()
    body= models.TextField()
    date=models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default="deafault.jpg",blank=True)

    def __str__(self):
        return self.title
    def snippet(self):
        return self.body[:50] + "..."

Blog/blog/accounts/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user= form.save()
            login(request,user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):

    if request.method=='POST':
       form =  AuthenticationForm(data=request.POST)
       if form.is_valid():
           user=form.get_user()
           login(request,user)
           return redirect('articles:list')
    else:

        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})


def logout_view(request):
    if request.method=='POST':
        logout(request)
        return redirect('articles:list')

Blog/blog/articles/views.py
from django.shortcuts import render
from .models import Article
from django.http import HttpResponse



# Create your views here.
def article_list(request):
    articles= Article.objects.all().order_by('date')
    return render(request,'articles/article_list.html',{"articles":articles})

def article_details(request,slug):
    #return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request,'articles/article_details.html',{"article": article})

Blog/blog/blog/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    #return HttpResponse('homepage')
    return render(request,'homepage.html')


def about(request):
    #return HttpResponse('about')
    return render(request,'about.html')

Blog/blog/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content%}
  <h1>LOGIN</h1>
  <form class="site-form" action="{% url 'accounts:login' %}" method="post">
  {% csrf_token  %}
  {{ form }}
  <input type="submit" value="login">
  </form>

{% endblock %}

Blog/blog/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content%}
  <h1>Sign Up</h1>
  <form class="site-form" action="/accounts/signup/" method="post">
  {% csrf_token  %}
  {{ form }}
  <input type="submit" value="SIGNUP">
  </form>

{% endblock %}

Blog/blog/articles/templates/articles/article_details.html
{% extends 'base_layout.html'%}

{% block content %}
<div class ="article_detail">
  <div class =" article">
    <img src="{{article.thumb.url}}">
    <h2>{{article.title}}</h2>
    <p>{{article.body}}</p>
    <p>{{article.date}}</p>
  </div>
</div>
{% endblock %}

Blog/blog/articles/templates/articles/article_list.html
{% extends 'base_layout.html'%}

{% block content %}
    <h1>Article List</h1>
    <div class = "articles">
      {% for article in articles %}
      <div class="article">
        <h6><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h6>
        <p>{{article.snippet}}</p>
        <p>{{article.date}}</p>
      </div>
      {% endfor %}
    </div>
{% endblock %}

Blog/blog/templates/about.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>AboutPage</title>
  </head>
  <body>
    <h1>AboutPage</h1>
  </body>
</html>

Blog/blog/templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Articles</title>
    <link rel ="stylesheet" href="{% static 'styles.css' %}">
  </head>
  <body>
  <header class="wrapper">
     <h1><a href ="{% url 'articles:list' %}"><img src= "{% static 'logo1.jpg'%}" width="100"  height="100"/></a></h1>
        <nav>
            <ul>
                <li>
                     <form class ="logout-link" action="{% url 'accounts:logout' %}" method="POST">
                    {% csrf_token %}
                    <button type="submit">LOGOUT</button>
                    </form>
                </li>
            </ul>
        </nav>

  </header>
    <div class="wrappper">

      {% block content %}
      {% endblock %}
  </div>
  </body>
</html>

Blog/blog/templates/homepage.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>homepage</title>
  </head>
  <body>
    <h1>HOMEPAGE</h1>
  </body>
</html>